version: '3.8'

services:
  backend:
    build: .
    container_name: travel-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - travel-app-network
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:alpine
    container_name: travel-redis
    networks:
      - travel-app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: travel-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - travel-app-network

networks:
  travel-app-network:
    external: true